import { Games } from './games';

export const GAMES_DATA: Games[] = [
  {
    id: '1',
    title: '7 cudów świata',
    price: 49.99,
    img: 'p1.jpg',
    short_description: 'Przejmij kontrolę nad jednym z siedmiu potężnych miast starożytnego świata w grze "7 Cudów Świata". Zbieraj surowce, rozwijaj miasto, buduj potęgę militarną i knuj intrygujące układy handlowe. Poprowadź swoją cywilizację do chwały, wznosząc imponujące cuda architektoniczne. To strategiczne wyzwanie, które łączy prostotę z dynamiczną rozgrywką, pozwalając ci zapisać swoje imię na kartach historii.',
    long_description: 'Stań na czele jednego z siedmiu wielkich miast starożytnego świata, kierując swoim ludem do poteżnej cywilizacji. Gromadź zasoby z bogactw swojej ziemi, uczestnicz w niekończącym się wyścigu rozwoju, knuj intrygujące układy handlowe i kuj potęgę militarystyczną. Wytyczaj niezatarty szlak w historii, konstruując monumentalne cuda architektoniczne, które przetrwają próbę czasu!',
    gametype1: 'Starożytność',
    published: 2020,
    max_players: 7,
    age: 14,
    likes: 7,
  },
  {
    id: '2',
    title: 'The Witcher: Old World',
    price: 29.99,
    img: 'p2.png',
    short_description: 'Posiądź postać doświadczonego łowcy potworów i odkryj fascynujący świat znanego z uniwersum Wiedźmina!',
    long_description: 'Witcher: Old World to fascynująca gra planszowa, przenosząca graczy do pełnego niebezpieczeństw świata wiedźmińskiego. Odkrywaj tajemnicze zakątki, staw czoła mrocznym sekretom i zagrożeniom w czasach, gdy plagą potworów nawiedzał Kontynent. Gra rozgrywa się przed wydarzeniami z sagi o Geralcie z Rivii, w epoce, gdy jedynymi skutecznymi przeciwnikami byli wiedźmini – wyszkoleni zabójcy potworów.',
    gametype1: 'Fantasy',
    published: 2023,
    max_players: 5,
    age: 16,
    likes: 13,
  },
  {
    id: '3',
    title: 'Pandemic',
    price: 44.99,
    img: 'p2.png',
    short_description: 'Walcz z globalną pandemią, współpracując z innymi graczami, by ocalić świat!',
    long_description: 'Pandemic to kooperacyjna gra planszowa, w której gracze razem walczą z globalną pandemią. Współpracujcie, aby znaleźć lekarstwo, kontrolować zarażenia i ocalić świat przed groźnymi chorobami!',
    gametype1: 'Kooperacyjna',
    published: 2008,
    max_players: 4,
    age: 12,
    likes: 30,
  },
  {
    id: '4',
    title: 'Terraforming Mars',
    price: 54.99,
    img: 'p2.png',
    short_description: 'Przekształć Marsa, rozwijając infrastrukturę i tworząc życie na Czerwonej Planecie!',
    long_description: 'Terraforming Mars to strategiczna gra planszowa, w której gracze współzawodniczą o terraformowanie i rozwój Marsa. Buduj infrastrukturę, twórz nowe ekosystemy i ulepszaj planetę, aby umożliwić życie na Czerwonej Planecie!',
    gametype1: 'Strategiczna',
    published: 2016,
    max_players: 5,
    age: 14,
    likes: 28,
  },
  {
    id: '5',
    title: 'Gloomhaven',
    price: 99.99,
    img: 'p2.png',
    short_description: 'Wyrusz w niezapomnianą przygodę jako najemnik w mrocznym i bogatym świecie fantasy!',
    long_description: 'Gloomhaven to epicka gra planszowa, oferująca setki godzin rozgrywki w bogatym świecie fantasy. Przejmij kontrolę nad postacią najemnika, podejmuj decyzje, eksploruj świat, walcz z potworami i wybieraj własną przygodę!',
    gametype1: 'Fantasy',
    published: 2017,
    max_players: 4,
    age: 14,
    likes: 35,
  },
  {
    id: '6',
    title: 'Azul',
    price: 29.99,
    img: 'p2.png',
    short_description: 'Twórz piękne wzory ceramiczne, zbieraj punkty i zostań mistrzem rzemieślniczej sztuki!',
    long_description: 'Azul to strategiczna gra planszowa, w której gracze rywalizują o stworzenie najbardziej estetycznych wzorów ceramicznych. Wybieraj kafelki, układaj wzory, zdobywaj punkty i zostań mistrzem rzemieślniczej sztuki!',
    gametype1: 'Strategiczna',
    published: 2017,
    max_players: 4,
    age: 8,
    likes: 20,
  },
  {
    id: '7',
    title: 'Wingspan',
    price: 49.99,
    img: 'p2.png',
    short_description: 'Odkryj fascynujący świat ptaków, budując unikalne ekosystemy i zdobywając punkty!',
    long_description: 'Wingspan to strategiczna gra planszowa, w której gracze budują unikalne ekosystemy dla różnorodnych gatunków ptaków. Zdobywaj punkty poprzez rozmieszczenie ptaków, zbieranie jaj i wykorzystywanie unikalnych umiejętności, odkrywając fascynujący świat przyrody!',
    gametype1: 'Przyrodnicza',
    published: 2019,
    max_players: 5,
    age: 10,
    likes: 28,
  },
  {
    id: '8',
    title: 'Scythe',
    price: 59.99,
    img: 'p2.png',
    short_description: 'Wciel się w przywódcę frakcji i zmierz się z rywalami, rozwijając swoje imperium!',
    long_description: 'Scythe to strategiczna gra planszowa osadzona w alternatywnej Europie lat 20. XX wieku. Rywalizuj z innymi graczami, rozwijając swoje imperium, zbierając zasoby, wznosząc mechy i zdobywając terytoria. Przygotuj się na wojnę i sprytne zagrania, aby osiągnąć sukces!',
    gametype1: 'Alternatywna historia',
    published: 2016,
    max_players: 7,
    age: 14,
    likes: 35,
  },
  {
    id: '9',
    title: 'Everdell',
    price: 45.99,
    img: 'p2.png',
    short_description: 'Odbuduj swoją społeczność zwierząt, rozwijając swoje królestwo w magicznym lesie Everdell!',
    long_description: 'Everdell to urocza gra planszowa, w której gracze budują swoje królestwo w magicznym lesie, odbudowując społeczność zwierząt. Zbieraj surowce, rekrutuj postaci i rozwijaj swoją wioskę, odkrywając tajemnice lesnego świata Everdell!',
    gametype1: 'Fantasy',
    published: 2018,
    max_players: 4,
    age: 12,
    likes: 22,
  },
  {
    id: '10',
    title: 'Arkham Horror: Gra karciana',
    price: 34.99,
    img: 'p2.png',
    short_description: 'Wciel się w badacza nadnaturalnego, odkrywając straszne tajemnice Arkham!',
    long_description: 'Arkham Horror: Gra karciana to gra karciana osadzona w uniwersum mitów H.P. Lovecrafta. Wciel się w rolę badacza nadnaturalnego, odkrywaj tajemnice Arkham, walcz z bestiami i przeciwnościami losu, starając się przetrwać koszmarne zdarzenia!',
    gametype1: 'Horror',
    published: 2016,
    max_players: 2,
    age: 14,
    likes: 18,
  },
  {
    id: '11',
    title: 'Catan',
    price: 39.99,
    img: 'p2.png',
    short_description: 'Zbuduj swoje osadnictwo, handluj z innymi graczami i zdobądź przewagę w grze o zasoby!',
    long_description: 'Catan to klasyczna gra planszowa, w której gracze rywalizują o rozbudowę swojego osadnictwa na niezamieszkałej wyspie. Handluj zasobami, rozwijaj się, buduj drogi i osady, zdobywając przewagę nad innymi graczami!',
    gametype1: 'Strategiczna',
    published: 1995,
    max_players: 4,
    age: 10,
    likes: 25,
  },
  {
    id: '12',
    title: 'Tajniacy: Spisek',
    price: 29.99,
    img: 'p2.png',
    short_description: 'Odkryj tajemnice spisku, zdradź sojuszników i wygrywaj dla swojej frakcji!',
    long_description: 'Tajniacy: Spisek to gra oparta na blefie, intrydze i dedukcji. Gracze wcielają się w role agentów, próbując odkryć tajemniczy spisek. Zdradzaj sojuszników, przekonuj innych do swojej frakcji i wygrywaj w tej emocjonującej grze!',
    gametype1: 'Dedukcyjna',
    published: 2016,
    max_players: 8,
    age: 12,
    likes: 17,
  },
  {
    id: '13',
    title: 'Dixit',
    price: 34.99,
    img: 'p2.png',
    short_description: 'Zgadnij, które zdjęcie pasuje do opowieści, tworząc magiczną atmosferę kreatywności!',
    long_description: 'Dixit to kreatywna gra planszowa, w której gracze tworzą opowieści, odnosząc się do tajemniczych obrazków na kartach. Zgadnij, które zdjęcie odpowiada opowieści, stwarzając magiczną i kreatywną atmosferę pełną wyobraźni!',
    gametype1: 'Kreatywna',
    published: 2008,
    max_players: 6,
    age: 8,
    likes: 21,
  },
  {
    id: '14',
    title: 'Codenames',
    price: 19.99,
    img: 'p2.png',
    short_description: 'Odkrywaj tajne słowa, współpracując z zespołem, aby wygrać w tej intrygującej grze słownej!',
    long_description: 'Codenames to gra słowna, w której gracze próbują odgadnąć tajne słowa na planszy za pomocą podpowiedzi udzielanych przez swojego agenta. Współpracuj z zespołem, wymyślaj skuteczne podpowiedzi i odkrywaj słowa, unikając przeciwnych kart!',
    gametype1: 'Słowna',
    published: 2015,
    max_players: 8,
    age: 14,
    likes: 24,
  },
  {
    id: '15',
    title: 'Splendor',
    price: 27.99,
    img: 'p2.png',
    short_description: 'Zbieraj klejnoty, handluj i rozwijaj swoją działalność, by stać się najbardziej wpływowym kupcem!',
    long_description: 'Splendor to ekonomiczna gra planszowa, w której gracze rywalizują o zdobycie klejnotów, handlując, rozwijając swoje działalności i stając się wpływowymi kupcami. Zbieraj karty, zdobywaj punkty i osiągnij sukces w tej strategicznej grze!',
    gametype1: 'Ekonomiczna',
    published: 2014,
    max_players: 4,
    age: 10,
    likes: 26,
  },
];
